### ISSUE TITLE
Onjuist datatype in shacl

### ISSUE THREAD

**Issue by fzand** [Geonovum/NL-SBB#7]
In de tabel 4.3.2 Specificatie Begrip is het type van “naam” rdf:langString. In de shacl is dit xsd:String.

Moet volgens @Bakkej zijn: `skosapnl:Concept-label sh:datatype rdf:langString`.

**Comment by fterpstra** [comment]
We passen de SHACL aan om in lijn te zijn met de standaard

**Comment by fterpstra** [comment]
Indien met deze aanpassing validatie niet goed werkt (dus de oorspronkelijke SHACL heeft gelijk) dan moeten we de standaard aanpassen.
